# Generated by Django 2.2.5 on 2019-10-06 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_acount',
            fields=[
                ('uname', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('upass', models.CharField(max_length=100)),
            ],
        ),
    ]
