# Generated by Django 2.2.5 on 2019-10-06 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_user_acount_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_acount',
            name='nickname',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
