# Generated by Django 2.2.5 on 2019-10-07 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20191006_2040'),
    ]

    operations = [
        migrations.CreateModel(
            name='orders',
            fields=[
                ('order_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('otime', models.DateTimeField()),
                ('customer', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=11)),
                ('total_money', models.CharField(max_length=15)),
                ('target_addr', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='foods',
            name='fid',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='user_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realname', models.CharField(max_length=100, unique=True)),
                ('phone', models.CharField(max_length=11)),
                ('target_addr', models.CharField(max_length=255)),
                ('remarks', models.CharField(max_length=255, null=True)),
                ('nickname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user_acount', to_field='nickname')),
            ],
        ),
        migrations.CreateModel(
            name='order_items',
            fields=[
                ('oi_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('oname', models.CharField(max_length=100)),
                ('onumber', models.IntegerField()),
                ('oprice', models.CharField(max_length=15)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.orders')),
            ],
        ),
    ]
