# Generated by Django 2.2.5 on 2019-10-07 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20191007_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foods',
            name='fid',
            field=models.AutoField(auto_created=1000, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order_items',
            name='oi_id',
            field=models.AutoField(auto_created=10000, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order_items',
            name='oprice',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='orders',
            name='total_money',
            field=models.CharField(max_length=50),
        ),
    ]
