# Generated by Django 2.2.5 on 2019-10-07 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20191007_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='otime',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='phone',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='realname',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='target_addr',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
