# Generated by Django 2.2.5 on 2019-10-09 08:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20191008_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='nickname',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
